---
# configuring an ubuntu server
- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - ansible_ssh_host_key_checking: False
    - ansible_user: ubuntu # TODO

  pre_tasks:
    # - name: "wait 600 seconds for target connection to become reachable/usable."
    #   wait_for_connection:
    #     timeout: 600

    - name: "install python for Ansible."
      apt:
        name: python3
        become: true
      # Your code here
    - debug:
        msg: "welp"


  roles:
    # Your code here
    - configure-server
